### ISSUE TITLE
Plugin conflict w/ McMMO Combat Level & other minor issues

### ISSUE THREAD

**Issue by jsgunman** [mcMMO-Dev/mcMMO-TagAPI#1]
Upon installing both McMMO Tag API and McMMO Combat Level onto my server, I have found a few issues. 

First, when a user is in the same party as you, is opped, has a nickname that uses color codes, or is in an allied party, the combat level from the other plugin shows as 0, regardless of the user's actual level. 

Second, when users have colored tags, their skin will sometimes not show up. 

Third, is it possible to make it so being opped or having a nickname will not affect the user's tag, and only being in a party or an allied party will? 

Thank you in advanced for your help.

**Comment by TfT-02** [comment]
> Upon installing both McMMO Tag API and McMMO Combat Level onto my server, I have found a few issues. 
> First, when a user is in the same party as you, is opped, has a nickname that uses color codes, or is in an allied party, the combat level from the other plugin shows as 0, regardless of the user's actual level. 

This isn't an issue with mcMMO TagAPI and mcMMO CombatLevels, but rather with TagAPI and mcMMOCombatLevel in general. If a player has a colored nameplate, the scoreboard messes up. See https://github.com/mcMMO-Dev/mcMMO/issues/1410
We're trying to figure it out, but haven't had much luck so far.

> Second, when users have colored tags, their skin will sometimes not show up. 

Which version of MC are you running? This is a side effect from using TagAPI to change the players nameplate and include colors. With latest MC versions, due to changes to the way player usernames are validated - TagAPI doesn't work as well as it used to do.

> Third, is it possible to make it so being opped or having a nickname will not affect the user's tag, and only being in a party or an allied party will? 

mcMMO-TagAPI does only change the players name tag when in a party. If you are seeing a player's display name/ nickname above their head - then you must be running another plugin which is doing this.

**Comment by TfT-02** [comment]
Closed due to inactivity.
